# Use postgres/example user/password credentials
version: '3.1'

services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: nest
networks:
  test: